/* Generated By:JavaCC: Do not edit this line. maguConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface maguConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TK_FORWARD = 1;
  /** RegularExpression Id. */
  int TK_LEFT = 2;
  /** RegularExpression Id. */
  int TK_RIGHT = 3;
  /** RegularExpression Id. */
  int TK_PENCILUP = 4;
  /** RegularExpression Id. */
  int TK_PENCILDOWN = 5;
  /** RegularExpression Id. */
  int TK_MOVE = 6;
  /** RegularExpression Id. */
  int TK_HOME = 7;
  /** RegularExpression Id. */
  int TK_CURVE = 8;
  /** RegularExpression Id. */
  int TK_INPUT = 9;
  /** RegularExpression Id. */
  int TK_PRINT = 10;
  /** RegularExpression Id. */
  int TK_WHILE = 11;
  /** RegularExpression Id. */
  int TK_IF = 12;
  /** RegularExpression Id. */
  int TK_ELSE = 13;
  /** RegularExpression Id. */
  int TK_ARR = 14;
  /** RegularExpression Id. */
  int TK_FUNC = 15;
  /** RegularExpression Id. */
  int TK_MAIN = 16;
  /** RegularExpression Id. */
  int TK_NE = 17;
  /** RegularExpression Id. */
  int TK_EQT = 18;
  /** RegularExpression Id. */
  int TK_LT = 19;
  /** RegularExpression Id. */
  int TK_GT = 20;
  /** RegularExpression Id. */
  int TK_EQ = 21;
  /** RegularExpression Id. */
  int TK_LPAR = 22;
  /** RegularExpression Id. */
  int TK_RPAR = 23;
  /** RegularExpression Id. */
  int TK_LBRACKET = 24;
  /** RegularExpression Id. */
  int TK_RBRACKET = 25;
  /** RegularExpression Id. */
  int TK_LBRACE = 26;
  /** RegularExpression Id. */
  int TK_RBRACE = 27;
  /** RegularExpression Id. */
  int TK_COMMA = 28;
  /** RegularExpression Id. */
  int TK_PLUS = 29;
  /** RegularExpression Id. */
  int TK_MINUS = 30;
  /** RegularExpression Id. */
  int TK_MULT = 31;
  /** RegularExpression Id. */
  int TK_DIV = 32;
  /** RegularExpression Id. */
  int TK_CTE_I = 33;
  /** RegularExpression Id. */
  int TK_ID = 34;
  /** RegularExpression Id. */
  int TK_STRING = 35;
  /** RegularExpression Id. */
  int QUOTE = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<TK_FORWARD>",
    "<TK_LEFT>",
    "<TK_RIGHT>",
    "<TK_PENCILUP>",
    "<TK_PENCILDOWN>",
    "<TK_MOVE>",
    "<TK_HOME>",
    "<TK_CURVE>",
    "<TK_INPUT>",
    "<TK_PRINT>",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"arr\"",
    "\"func\"",
    "\"main\"",
    "\"<>\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<TK_CTE_I>",
    "<TK_ID>",
    "<TK_STRING>",
    "\"\\\"\"",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
